### ISSUE TITLE
Module won't build on Windows with Node <9.2.0

### ISSUE THREAD

**Issue by cobarx** [ronomon/direct-io#2]
Thanks again for updating the Windows library. We are using Electron to build a Windows & OS X app, and since Electron ships with Node 7.9.0 built in the module won't compile (error shown below).

I realize O_DIRECT will only work on Node 9.2.0+, however it would be great to add least be able to install the library. Right now we have to use some crazy try / catch tricks to avoid errors when we require the library since we need it for OS X and even with that have some issues with newer versions of npm.

```
PS C:\Users\GoChip\gochip\GoChipPlayer-Electron\app> npm install
                                                                                                                        ChipPlayer-Electron\app\node_modules\.staging\@ronomon\queue-4d47975e\nod
> @ronomon/direct-io@2.3.0 install C:\Users\GoChip\gochip\GoChipPlayer-Electron\app\node_modules\@ronomon\direct-io
> node-gyp rebuild

C:\Users\GoChip\gochip\GoChipPlayer-Electron\app\node_modules\@ronomon\direct-io>if not defined npm_config_node_gyp (node "C:\Users\GoChip\scoop\apps\nodejs\7.10.1\node_modules\npm\bin\node-gyp-
bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Warning: Missing input files:
C:\Users\GoChip\gochip\GoChipPlayer-Electron\app\node_modules\@ronomon\direct-io\build\Release\binding.node
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  binding.cc
  win_delay_load_hook.cc
..\binding.cc(145): error C3861: 'uv_get_osfhandle': identifier not found [C:\Users\GoChip\gochip\GoChipPlayer-Electron\app\node_modules\@ronomon\direct-io\build\binding.vcxproj]
..\binding.cc(374): error C3861: 'uv_get_osfhandle': identifier not found [C:\Users\GoChip\gochip\GoChipPlayer-Electron\app\node_modules\@ronomon\direct-io\build\binding.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\GoChip\scoop\apps\nodejs\7.10.1\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Users\\GoChip\\scoop\\apps\\nodejs\\current\\node.exe" "C:\\Users\\GoChip\\scoop\\apps\\nodejs\\7.10.1\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuil
d"
gyp ERR! cwd C:\Users\GoChip\gochip\GoChipPlayer-Electron\app\node_modules\@ronomon\direct-io
gyp ERR! node -v v7.10.1
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Users\\GoChip\\scoop\\apps\\nodejs\\current\\node.exe" "C:\\Users\\GoChip\\scoop\\apps\\nodejs\\current\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v7.10.1
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! @ronomon/direct-io@2.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
```

**Comment by jorangreef** [comment]
Sure, which features of `direct-io` are you using on Windows?

`uv_get_osfhandle` is required on Windows for getting block device information and for toggling `FSCTL_LOCK_VOLUME`.

`uv_get_osfhandle` has been in libuv since version 1.12.0 (2017.05.31) and in Node [since May last year](https://github.com/nodejs/node/commit/edd541957f6bb6fa4ccb56bd1f878172f631ce36). Libuv 1.12 was even backported to Node's 6 LTS version as far as I know.

**Comment by cobarx** [comment]
Electron just released a version based on Node 8.2.1, so I upgraded and that handled it.

What's involved in building a newer version of libuv? I should be able to build it no problem, but I'm not sure how I'd integrate it into our app. We just would like to be able to use `O_DIRECT` on Windows.

**Comment by jorangreef** [comment]
> What's involved in building a newer version of libuv? I should be able to build it no problem, but I'm not sure how I'd integrate it into our app. We just would like to be able to use O_DIRECT on Windows.

You would need to rebuild Electron's version of Node with a newer libuv. It may be easier to rather encourage Electron to release faster.
